[package]
name = "tarea3"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "http_client"
path = "src/http_client.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
